package com.aicraft;

import com.aicraft.ai.AIManager;
import com.aicraft.commands.*;
import com.aicraft.database.DatabaseManager;
import com.aicraft.factions.FactionManager;
import com.aicraft.gui.QuestTrackerGUI;
import com.aicraft.listeners.ChatListener;
import com.aicraft.listeners.NPCDamageListener;
import com.aicraft.listeners.PlayerInteractListener;
import com.aicraft.listeners.QuestProgressListener;
import com.aicraft.memory.MemoryManager;
import com.aicraft.minimap.MinimapCommand;
import com.aicraft.minimap.MinimapManager;
import com.aicraft.npcs.NPCManager;
import com.aicraft.npcs.NPCSpawner;
import com.aicraft.npcs.behavior.WanderingManager;
import com.aicraft.npcs.building.NPCHomeBuilder;
import com.aicraft.npcs.building.NPCSettlementDefense;
import com.aicraft.npcs.social.NPCSocialManager;
import com.aicraft.quests.QuestManager;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.logging.Level;

/**
 * AICompanions - AI-powered NPCs with personalities, factions, quests, and dynamic conversations
 *
 * Features:
 * - NPCs with unique personalities and backstories generated by AI
 * - Faction system with relationships and conflicts
 * - Wandering NPCs that can die from monsters or hostile NPCs
 * - Persistent memory of conversations with players
 * - Dynamic quest generation
 */
public class AICompanions extends JavaPlugin {

    private static AICompanions instance;

    private DatabaseManager databaseManager;
    private AIManager aiManager;
    private NPCManager npcManager;
    private FactionManager factionManager;
    private MemoryManager memoryManager;
    private QuestManager questManager;
    private WanderingManager wanderingManager;
    private NPCSpawner npcSpawner;
    private QuestTrackerGUI questTrackerGUI;
    private NPCSocialManager socialManager;
    private NPCHomeBuilder homeBuilder;
    private NPCSettlementDefense settlementDefense;
    private ChatListener chatListener;
    private MinimapManager minimapManager;

    @Override
    public void onEnable() {
        instance = this;

        // Save default config
        saveDefaultConfig();

        getLogger().info("===========================================");
        getLogger().info("  AICompanions - Loading...");
        getLogger().info("===========================================");

        try {
            // Initialize managers in order
            initializeManagers();

            // Register commands
            registerCommands();

            // Register event listeners
            registerListeners();

            // Start background tasks
            startTasks();

            getLogger().info("===========================================");
            getLogger().info("  AICompanions - Successfully Loaded!");
            getLogger().info("  NPCs: " + npcManager.getNPCCount());
            getLogger().info("  Factions: " + factionManager.getFactionCount());
            getLogger().info("  AI Provider: " + aiManager.getProviderName());
            getLogger().info("===========================================");

        } catch (Exception e) {
            getLogger().log(Level.SEVERE, "Failed to initialize AICompanions!", e);
            getServer().getPluginManager().disablePlugin(this);
        }
    }

    @Override
    public void onDisable() {
        getLogger().info("AICompanions - Shutting down...");

        // Save all data
        if (npcManager != null) {
            npcManager.saveAll();
        }
        if (memoryManager != null) {
            memoryManager.saveAll();
        }
        if (questManager != null) {
            questManager.saveAll();
        }

        // Close database connection
        if (databaseManager != null) {
            databaseManager.close();
        }

        // Stop wandering tasks
        if (wanderingManager != null) {
            wanderingManager.stop();
        }

        // Stop spawner
        if (npcSpawner != null) {
            npcSpawner.stop();
        }

        // Stop social manager
        if (socialManager != null) {
            socialManager.stop();
        }

        // Stop home builder
        if (homeBuilder != null) {
            homeBuilder.stop();
        }

        // Stop settlement defense
        if (settlementDefense != null) {
            settlementDefense.stop();
        }

        // Stop minimap manager
        if (minimapManager != null) {
            minimapManager.stop();
        }

        getLogger().info("AICompanions - Goodbye!");
    }

    private void initializeManagers() {
        getLogger().info("Initializing database...");
        databaseManager = new DatabaseManager(this);
        databaseManager.initialize();

        getLogger().info("Initializing AI manager...");
        aiManager = new AIManager(this);

        getLogger().info("Initializing faction manager...");
        factionManager = new FactionManager(this, databaseManager);
        factionManager.loadFactions();

        getLogger().info("Initializing memory manager...");
        memoryManager = new MemoryManager(this, databaseManager);

        getLogger().info("Initializing NPC manager...");
        npcManager = new NPCManager(this, databaseManager, aiManager, factionManager);
        npcManager.loadNPCs();

        getLogger().info("Initializing quest manager...");
        questManager = new QuestManager(this, databaseManager, aiManager);

        getLogger().info("Initializing wandering manager...");
        wanderingManager = new WanderingManager(this, npcManager, factionManager);

        getLogger().info("Initializing NPC spawner...");
        npcSpawner = new NPCSpawner(this, npcManager, factionManager);

        getLogger().info("Initializing NPC social manager...");
        socialManager = new NPCSocialManager(this, npcManager);

        getLogger().info("Initializing NPC home builder...");
        homeBuilder = new NPCHomeBuilder(this, npcManager);

        getLogger().info("Initializing settlement defense system...");
        settlementDefense = new NPCSettlementDefense(this, npcManager, homeBuilder);

        getLogger().info("Initializing minimap manager...");
        minimapManager = new MinimapManager(this, npcManager, questManager);
    }

    private void registerCommands() {
        getCommand("npc").setExecutor(new NPCCommand(this, npcManager, aiManager, factionManager));
        getCommand("faction").setExecutor(new FactionCommand(this, factionManager));

        // Initialize Quest GUI and wire it to the command
        questTrackerGUI = new QuestTrackerGUI(this, questManager, npcManager);
        QuestCommand questCommand = new QuestCommand(this, questManager);
        questCommand.setQuestGUI(questTrackerGUI);
        getCommand("quest").setExecutor(questCommand);

        // Register quests alias
        if (getCommand("quests") != null) {
            getCommand("quests").setExecutor(questCommand);
        }

        getCommand("aiconfig").setExecutor(new AIConfigCommand(this, aiManager));

        // Register minimap command
        MinimapCommand minimapCommand = new MinimapCommand(minimapManager);
        getCommand("minimap").setExecutor(minimapCommand);
        getCommand("minimap").setTabCompleter(minimapCommand);
    }

    private void registerListeners() {
        // Store ChatListener reference so PlayerInteractListener can access it
        chatListener = new ChatListener(this, npcManager, aiManager, memoryManager);
        getServer().getPluginManager().registerEvents(chatListener, this);
        getServer().getPluginManager().registerEvents(new PlayerInteractListener(this, npcManager), this);
        getServer().getPluginManager().registerEvents(new NPCDamageListener(this, npcManager, factionManager), this);
        getServer().getPluginManager().registerEvents(new QuestProgressListener(this, questManager), this);
    }

    private void startTasks() {
        // Start wandering behavior
        if (getConfig().getBoolean("npcs.wandering.enabled", true)) {
            wanderingManager.start();
        }

        // Auto-save task
        int saveInterval = getConfig().getInt("performance.save-interval", 5) * 60 * 20; // Convert to ticks
        getServer().getScheduler().runTaskTimerAsynchronously(this, () -> {
            npcManager.saveAll();
            memoryManager.saveAll();
            questManager.saveAll();
        }, saveInterval, saveInterval);

        // NPC entity refresh task - fixes stale entity mappings after chunk load/unload
        getServer().getScheduler().runTaskTimer(this, () -> {
            npcManager.refreshEntityMappings();
        }, 200L, 200L); // Every 10 seconds

        // Gossip task (NPCs share info about players)
        if (getConfig().getBoolean("memory.gossip-enabled", true)) {
            int gossipInterval = getConfig().getInt("memory.gossip-interval", 30) * 60 * 20;
            getServer().getScheduler().runTaskTimerAsynchronously(this, () -> {
                memoryManager.processGossip(npcManager.getAllNPCs());
            }, gossipInterval, gossipInterval);
        }

        // Start auto-spawning NPCs
        if (getConfig().getBoolean("spawning.enabled", true)) {
            npcSpawner.start();
        }

        // Start NPC social interactions (relationships, cultist chanting)
        if (getConfig().getBoolean("npcs.social.enabled", true)) {
            socialManager.start();
        }

        // Start NPC home building
        if (getConfig().getBoolean("npcs.building.enabled", true)) {
            homeBuilder.start();
        }

        // Start settlement defense system (guards, walls)
        if (getConfig().getBoolean("settlements.defense.enabled", true)) {
            settlementDefense.start();
        }

        // Start minimap manager
        if (getConfig().getBoolean("minimap.enabled", true)) {
            minimapManager.start();
        }
    }

    public void reload() {
        reloadConfig();
        aiManager.reload();
        factionManager.reload();
    }

    // Static accessor
    public static AICompanions getInstance() {
        return instance;
    }

    // Getters for managers
    public DatabaseManager getDatabaseManager() {
        return databaseManager;
    }

    public AIManager getAIManager() {
        return aiManager;
    }

    public NPCManager getNPCManager() {
        return npcManager;
    }

    public FactionManager getFactionManager() {
        return factionManager;
    }

    public MemoryManager getMemoryManager() {
        return memoryManager;
    }

    public QuestManager getQuestManager() {
        return questManager;
    }

    public WanderingManager getWanderingManager() {
        return wanderingManager;
    }

    public NPCSpawner getNPCSpawner() {
        return npcSpawner;
    }

    public NPCSocialManager getSocialManager() {
        return socialManager;
    }

    public NPCHomeBuilder getHomeBuilder() {
        return homeBuilder;
    }

    public NPCSettlementDefense getSettlementDefense() {
        return settlementDefense;
    }

    public ChatListener getChatListener() {
        return chatListener;
    }

    public MinimapManager getMinimapManager() {
        return minimapManager;
    }

    public boolean isDebug() {
        return getConfig().getBoolean("performance.debug", false);
    }

    public void debug(String message) {
        if (isDebug()) {
            getLogger().info("[DEBUG] " + message);
        }
    }
}
